Imagem ajustada!
sysadminas/sysadminas-site pull request #10
Opened 2020-10-04 00:30 UTC by sidneymiranda

Olá, espero que atenda às suas expectativas. Fico grato em poder contruir.

2020-10-04 04:09 UTC, sidneymiranda commented
Feito! issue - Fazer integração com o sympla na aba "Eventos" #3

2020-10-07 23:47 UTC, brandonluizz requested changes

2020-10-07 23:47 UTC, brandonluizz commented on express/index.html
> +    <main id="main">
Olá Sidney, tudo bem? Muito obrigado pela contribuição, ficamos muito felizes!

Vi que deu um conflito na hora de mergear e acabou quebrando um pouco a área "Nossa historia", será que consegue arrumar essa parte para seguirmos com o merge?

Muito obrigado!

2020-10-08 00:05 UTC, sidneymiranda commented on express/index.html
> +    <main id="main">
Onde exatamente quebrou?
![image](https://user-images.githubusercontent.com/39252967/95400324-be19f200-08e0-11eb-8a0e-3572f5942dbf.png)

2020-10-08 00:15 UTC, brandonluizz commented on express/index.html
> +    <main id="main">
Que estranho, aqui está dessa forma 
![image](https://user-images.githubusercontent.com/15144708/95400895-39c86e80-08e2-11eb-9e0f-8a128e57d8d4.png)

2020-10-08 00:22 UTC, brandonluizz commented on express/index.html
> +    <main id="main">
Eu fiz uma alteração na master do projeto agora a pouco e gerou uns conflitos aqui. Vou resolvê-los. 
Eu tive que alterar o tipo da indentação do projeto.

2020-10-08 00:25 UTC, sidneymiranda commented on express/index.html
> +    <main id="main">
Encontrei algumas sujeiras no html e css, detalhes como se fossem comentários, do tipo: >>>>> =====.
Verifica se resolveu.

2020-10-08 00:27 UTC, brandonluizz commented on express/index.html
> +    <main id="main">
Beleza! Quando acontece conflitos nos merge aparece isso pra saber os pontos dos conflitos. Valeu!

2020-10-08 00:55 UTC, brandonluizz requested changes
@sidneymiranda ainda ta quebrado. Olha só como está aqui.

Será que vc não consegue fazer o fork do projeto novamente e submeter outro PR?
Vc não será invalidado na hacktoberfest, é só para podermos mergear suas alterações.
Desculpa o inconveniente :/ 

![image](https://user-images.githubusercontent.com/15144708/95402981-6337c900-08e7-11eb-8919-5cd123fdd6ea.png)

2020-10-08 00:57 UTC, sidneymiranda commented
Nossa, comigo não está assim.
Sem problemas, farei um novo fork e verifico o que houve.

2020-10-08 01:06 UTC, sidneymiranda commented
Algumas referências, classes e/ou id, no css estão faltando. Por isso o layout está quebrando.
![image](https://user-images.githubusercontent.com/39252967/95403678-469c9080-08e9-11eb-9457-076d62d059fb.png)

2020-10-08 16:31 UTC, sidneymiranda commented
Olá, no html haviam duplicação da tag main, isso estava causando a duplicidade na sessão "Sobre nós".

Efetuei os ajustes e por aqui está tudo certo.

![image](https://user-images.githubusercontent.com/39252967/95487235-72138f80-096a-11eb-8373-c2be8c480562.png)

2022-09-30 22:07 UTC, closed without merging